INSERT INTO USER(ID, USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL) VALUES (1,'admin1', 'manager', '관리자1', '');
INSERT INTO USER(ID, USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL) VALUES (2,'admin2', 'manager', '관리자2', '');
INSERT INTO USER(ID, USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL) VALUES (3,'admin3', 'manager', '관리자3', '');